In [5]:
import pandas as pd
Data_df=pd.read_csv("atlcrime.csv")
Data_df

C:\Users\FORYY\AppData\Local\Temp\ipykernel_5260\3683457063.py:2: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  Data_df=pd.read_csv("atlcrime.csv")

,Unnamed: 0,crime,number,date,location,beat,neighborhood,npu,lat,long
0,0,LARCENY-NON VEHICLE,103040029,10/31/2010,610 SPRING ST NW,509,Downtown,M,33.77101,-84.38895
1,1,AUTO THEFT,103040061,10/31/2010,850 OAK ST SW,401,West End,T,33.74057,-84.41680
2,2,LARCENY-FROM VEHICLE,103040169,10/31/2010,1344 METROPOLITAN PKWY SW,301,Capitol View Manor,X,33.71803,-84.40774
3,3,AUTO THEFT,103040174,10/31/2010,1752 PRYOR RD SW,307,Betmar LaVilla,Y,33.70731,-84.39674
4,4,LARCENY-NON VEHICLE,103040301,10/31/2010,JOHN WESLEY DOBBS AVE NE / CORLEY ST NE,604,Old Fourth Ward,M,33.75947,-84.36626
...,...,...,...,...,...,...,...,...,...,...
270683,270683,BURGLARY-RESIDENCE,92442142,09/01/2009,1226 PORTLAND AVE SE,612,East Atlanta,W,33.73927,-84.34741
270684,270684,LARCENY-FROM VEHICLE,92442164,09/01/2009,317 PICKFAIR WAY SW,307,Lakewood Heights,Y,33.70436,-84.40013
270685,270685,LARCENY-NON VEHICLE,92448045,09/01/2009,6234 SPINE RD @ATRIUM,50,NaN,NaN,33.64068,-84.44204
270686,270686,LARCENY-NON VEHICLE,92440866,09/01/2009,30 WARREN ST,610,Kirkwood,O,33.75374,-84.32600
270687,270687,HOMICIDE,92440372058,09/01/2009,2860 MARTIN L KING JR DR SW,405,Harland Terrace,I,33.75399,-84.48138

In [13]:
neighborhood = 'Downtown' # Cambiar por el barrio que se quiera consultar
downtown_deaths = Data_df[Data_df['neighborhood'] == neighborhood] # Filtrar por barrio seleccionado y guardar en variable downtown_deaths
total_deaths_downtown = downtown_deaths['neighborhood'].value_counts()[neighborhood] # Sumar los valores de la columna neighborhood y guardar en variable total_deaths_downtown
print("Sumatorio de muertes en Downtown:", total_deaths_downtown) # Mostrar por pantalla el sumatorio de muertes en el barrio seleccionado
downtown_deaths # Mostrar tabla con los datos filtrados

Sumatorio de muertes en Downtown: 19743

,Unnamed: 0,crime,number,date,location,beat,neighborhood,npu,lat,long
0,0,LARCENY-NON VEHICLE,103040029,10/31/2010,610 SPRING ST NW,509,Downtown,M,33.77101,-84.38895
9,9,LARCENY-FROM VEHICLE,103040412,10/31/2010,229 PEACHTREE ST NE,509,Downtown,M,33.76040,-84.38746
14,14,RAPE,103040611,10/31/2010,210 PEACHTREE ST,508,Downtown,M,33.75946,-84.38769
15,15,LARCENY-NON VEHICLE,103040646,10/31/2010,610 SPRING ST NW,509,Downtown,M,33.77101,-84.38895
24,24,LARCENY-NON VEHICLE,103041004,10/31/2010,36 HARRIS ST NW,508,Downtown,M,33.76089,-84.38855
...,...,...,...,...,...,...,...,...,...,...
270591,270591,LARCENY-NON VEHICLE,92441429,09/01/2009,265 PEACHTREE ST SW,512,Downtown,M,33.74737,-84.39637
270600,270600,LARCENY-FROM VEHICLE,92441637,09/01/2009,150 CARNEGIE WAY NW,508,Downtown,M,33.75832,-84.38905
270624,270624,LARCENY-NON VEHICLE,92440245,09/01/2009,IVAN ALLEN JR BLVD NE / PEACHTREE ST NE,508,Downtown,M,33.76455,-84.38576
270650,270650,ROBBERY-PEDESTRIAN,92440827,09/01/2009,111 CONE ST,508,Downtown,M,33.75829,-84.38952
270665,270665,LARCENY-NON VEHICLE,92440987,09/01/2009,50 HURT PLZ SE,510,Downtown,M,33.75391,-84.38733